CREATE OR ALTER PROCEDURE API_CHANGE_PASSWORD
    @Email VARCHAR(255),
    @NewPassword VARCHAR(10)
AS
BEGIN
    UPDATE ADMIN_TABLE
    SET ADMIN_PASSWORD = @NewPassword
    WHERE ADMIN_EMAIL = @Email;
END
